import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"
import ClientLayout from "./ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  themeColor: "#ffae00",
}

export const metadata: Metadata = {
  title: "MYBGFX",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/favicon.png",
    shortcut: "/assets/images/favicon.png",
    apple: "/assets/images/favicon.png",
  },
  appleWebApp: {
    capable: true,
    title: "MYBGFX",
    statusBarStyle: "black-translucent",
  },
  openGraph: {
    title: "MYBGFX",
    description: "Generated by create next app",
    type: "website",
  },
  other: {
    "msapplication-TileColor": "#ffae00",
    "msapplication-TileImage": "/favicon.png",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}